import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://www.woodfortcases.com',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
      images: [
        'https://www.woodfortcases.com/brand/logo.webp',
        'https://www.woodfortcases.com/images/composite.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/power1_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/main_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/power1_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/main_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/power1_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/main_blackwood.jpg',
        'https://www.woodfortcases.com/images/wip_sanding_alt_blackwhite.jpg',
        'https://www.woodfortcases.com/brand/logo-icon_white.png',
      ],
    },
    {
      url: 'https://www.woodfortcases.com/cases',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.75,
      images: [
        'https://www.woodfortcases.com/images/genesis/tasoak/power1_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/main_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/power1_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/main_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/power1_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/main_blackwood.jpg',
      ],
    },
    {
      url: 'https://www.woodfortcases.com/about',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.75,
      images: [
        'https://www.woodfortcases.com/images/wip_closeup_blackwhite.jpg',
        'https://www.woodfortcases.com/images/wip_sanding_alt_blackwhite.jpg',
        'https://www.woodfortcases.com/images/wip_routing_blackwhite.jpg',
        'https://www.woodfortcases.com/images/wip_painting_blackwhite.jpg',
        'https://www.woodfortcases.com/images/wip_buffing_blackwhite.jpg',
        'https://www.woodfortcases.com/images/prototype_blackwhite.jpg',
      ],
    },
    {
      url: 'https://www.woodfortcases.com/cases/genesis/tasmanian-oak',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.75,
      images: [
        'https://www.woodfortcases.com/images/genesis/tasoak/main_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/power1_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/power2_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/rear_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/towering_alt_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/bare_left_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/bare_front_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/bare_back_tasoak.jpg',
        'https://www.woodfortcases.com/images/genesis/tasoak/bare_right_tasoak.jpg',
      ],
    },
    {
      url: 'https://www.woodfortcases.com/cases/genesis/walnut',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.75,
      images: [
        'https://www.woodfortcases.com/images/genesis/walnut/main_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/power1_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/power2_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/rear_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/towering_alt_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/bare_left_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/bare_front_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/bare_back_walnut.jpg',
        'https://www.woodfortcases.com/images/genesis/walnut/bare_right_walnut.jpg',
      ],
    },
    {
      url: 'https://www.woodfortcases.com/cases/genesis/blackwood',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.75,
      images: [
        'https://www.woodfortcases.com/images/genesis/blackwood/main_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/power1_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/power2_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/rear_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/towering_alt_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/bare_left_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/bare_front_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/bare_back_blackwood.jpg',
        'https://www.woodfortcases.com/images/genesis/blackwood/bare_right_blackwood.jpg',
      ],
    },
    {
      url: 'https://www.woodfortcases.com/contact',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://www.woodfortcases.com/policies/terms-of-service',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
    {
      url: 'https://www.woodfortcases.com/policies/refund-policy',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.75,
    },
  ];
}
