import s from './page.module.css';
import Section from '@/components/Section';
import type { Metadata } from 'next';

// import imageTasOakMain from '../../../../../public/images/genesis/tasoak/main_tasoak.jpg';
import imageBlackwoodMain from '../../../../../public/images/genesis/blackwood/main_blackwood.jpg';
// import imageWalnutMain from '../../../../../public/images/genesis/walnut/main_walnut.jpg';
// import imageTasOakPower1 from '../../../../../public/images/genesis/tasoak/power1_tasoak.jpg';
import imageBlackwoodPower1 from '../../../../../public/images/genesis/blackwood/power1_blackwood.jpg';
// import imageWalnutPower1 from '../../../../../public/images/genesis/walnut/power1_walnut.jpg';
// import imageTasOakPower2 from '../../../../../public/images/genesis/tasoak/power2_tasoak.jpg';
import imageBlackwoodPower2 from '../../../../../public/images/genesis/blackwood/power2_blackwood.jpg';
// import imageWalnutPower2 from '../../../../../public/images/genesis/walnut/power2_walnut.jpg';

import imageBlackwoodRear from '../../../../../public/images/genesis/blackwood/rear_blackwood.jpg';
import imageBlackwoodToweringAlt from '../../../../../public/images/genesis/blackwood/towering_alt_blackwood.jpg';
import imageBlackwoodBareLeft from '../../../../../public/images/genesis/blackwood/bare_left_blackwood.jpg';
import imageBlackwoodBareRight from '../../../../../public/images/genesis/blackwood/bare_right_blackwood.jpg';
import imageBlackwoodBareFront from '../../../../../public/images/genesis/blackwood/bare_front_blackwood.jpg';
import imageBlackwoodBareBack from '../../../../../public/images/genesis/blackwood/bare_back_blackwood.jpg';

import ProductGallery from '@/components/ProductGallery';

export const metadata: Metadata = {
  title: 'Genesis - Blackwood',
};

const Page = () => {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: 'Genesis PC Case (Blackwood) | Woodfort Cases',
    image:
      'https://www.woodfortcases.com/images/genesis/tasoak/main_tasoak.jpg',
    description:
      'Handmade wooden PC case made from Blackwood, a prized Australian timber that features golden rown tones meixed with some reds and darker streaks.',
    brand: {
      '@type': 'Brand',
      name: 'Woodfort Cases',
    },
    offers: {
      '@type': 'Offer',
      offerCount: 1,
      // TODO: CONSOLIDATE PRICE AMONGST ALL PAGES AND TILES
      price: 2800,
      priceCurrency: 'AUD',
      itemCondition: 'https://schema.org/NewCondition',
      availability: 'https://schema.org/InStock',
      url: 'https://www.woodfortcases.com/cases/genesis/blackwood',
      seller: {
        '@type': 'Organization',
        name: 'Woodfort Cases',
      },
    },
  };

  return (
    <Section tight>
      {/* Add JSON-LD to your page */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {/* ... */}
      <div className={s.productContainer}>
        <ProductGallery
          images={[
            { src: imageBlackwoodMain, alt: '' },
            { src: imageBlackwoodPower1, alt: '' },
            { src: imageBlackwoodPower2, alt: '' },
            { src: imageBlackwoodRear, alt: '' },
            { src: imageBlackwoodToweringAlt, alt: '' },
            { src: imageBlackwoodBareLeft, alt: '' },
            { src: imageBlackwoodBareFront, alt: '' },
            { src: imageBlackwoodBareBack, alt: '' },
            { src: imageBlackwoodBareRight, alt: '' },
          ]}
        />
        <div className={s.productDetails}>
          <span className={s.overTitle}>Mid Tower</span>
          <h1>Genesis - Blackwood</h1>
          <p className={s.price}>$2,800 AUD</p>
          {/* <span>Tax included.</span> */}
          <p>The Genesis is the case that marks the beginning of Woodfort.</p>
          <p>
            Embodying Woodfort&#39;s alignment with nature, four hand crafted
            wooden panels cover the cold aluminum structure beneath with the
            soothing glow of natural timber.
          </p>
          <p>
            This case is made from Blackwood, a prized Australian timber that
            features golden rown tones meixed with some reds and darker streaks.
          </p>
          <p>
            The wood has been finished with a durable and heat resistant varnish
            protecting the timber from the warmth generated by the compouter
            components and providing a lustrous satin to semi-gloss sheen.
          </p>
          <blockquote className={s.quote}>
            &#34;It seems to me that the natural world is the greatest source of
            excitement; the greatest source of visual beauty; the greatest
            source of intellectual interest. It is the greatest source of so
            much in life that makes life worth living.&#34;
          </blockquote>
          <span className={s.quoteSource}>- Sir David Attenborough</span>
          <h3>Disclaimer</h3>
          <p>
            This item is made of wood so the texture and colour tone will vary
            slightly from piece to piece.
          </p>
          <p>
            Lastly, this is a handmade product and as such minor imperfections
            may exist that betray my human fallibility.
          </p>
          {/* <Link href="/">Share</Link> */}
        </div>
      </div>
    </Section>
  );
};

export default Page;
