import s from './page.module.css';
import Section from '@/components/Section';
import type { Metadata } from 'next';

import imageWalnutMain from '../../../../../public/images/genesis/walnut/main_walnut.jpg';
import imageWalnutPower1 from '../../../../../public/images/genesis/walnut/power1_walnut.jpg';
import imageWalnutPower2 from '../../../../../public/images/genesis/walnut/power2_walnut.jpg';
import imageWalnutRear from '../../../../../public/images/genesis/walnut/rear_walnut.jpg';
import imageWalnutToweringAlt from '../../../../../public/images/genesis/walnut/towering_alt_walnut.jpg';
import imageWalnutBareLeft from '../../../../../public/images/genesis/walnut/bare_left_walnut.jpg';
import imageWalnutBareRight from '../../../../../public/images/genesis/walnut/bare_right_walnut.jpg';
import imageWalnutBareFront from '../../../../../public/images/genesis/walnut/bare_front_walnut.jpg';
import imageWalnutBareBack from '../../../../../public/images/genesis/walnut/bare_back_walnut.jpg';

import ProductGallery from '@/components/ProductGallery';

export const metadata: Metadata = {
  title: 'Genesis - Walnut | Woodfort Cases',
};

const Page = () => {
  return (
    <Section tight>
      <div className={s.productContainer}>
        <ProductGallery
          images={[
            { src: imageWalnutMain, alt: '' },
            { src: imageWalnutPower1, alt: '' },
            { src: imageWalnutPower2, alt: '' },
            { src: imageWalnutRear, alt: '' },
            { src: imageWalnutToweringAlt, alt: '' },
            { src: imageWalnutBareLeft, alt: '' },
            { src: imageWalnutBareFront, alt: '' },
            { src: imageWalnutBareBack, alt: '' },
            { src: imageWalnutBareRight, alt: '' },
          ]}
        />
        <div className={s.productDetails}>
          <span className={s.overTitle}>Mid Tower</span>
          <h1>Genesis - Walnut</h1>
          {/* <span>$2,800</span> */}
          {/* <span>Tax included.</span> */}
          <p>The Genesis is the case that marks the beginning of Woodfort.</p>
          <p>
            Embodying Woodfort's alignment with nature, four hand crafted wooden
            panels cover the cold aluminum structure beneath with the soothing
            glow of natural timber.
          </p>
          <p>
            This case is made from the recognisable American Walnut which
            displays deep chocolate brown colours.
          </p>
          <p>
            The wood has been finished with a durable and heat resistant varnish
            protecting the timber from the warmth generated by the compouter
            components and providing a lustrous satin to semi-gloss sheen.
          </p>
          <blockquote className={s.quote}>
            "It seems to me that the natural world is the greatest source of
            excitement; the greatest source of visual beauty; the greatest
            source of intellectual interest. It is the greatest source of so
            much in life that makes life worth living."
          </blockquote>
          <span className={s.quoteSource}>- Sir David Attenborough</span>
          <h3>Disclaimer</h3>
          <p>
            This item is made of wood so the texture and colour tone will vary
            slightly from piece to piece.
          </p>
          <p>
            Lastly, this is a handmade product and as such minor imperfections
            may exist that betray my human fallibility.
          </p>
          {/* <Link href="/">Share</Link> */}
        </div>
      </div>
    </Section>
  );
};

export default Page;
